# http://edmproddemo.ingress-nginx.edmtest-m1.edm.sashq-d.openstack.sas.com/modelPublish/models/32c38d2e-337b-479c-a9be-2c5778ba1835/dockerfile/content

FROM repulpmaster.unx.sas.com/viya-4-x64_oci_linux_2-docker/sas-decisions-runtime-components:1.50.30-20240117.1705515835418 as base
FROM repulpmaster.unx.sas.com/viya-4-x64_oci_linux_2-docker/sas-decisions-runtime-base:1.68.29-20240117.1705514528173
LABEL model container image
USER root
RUN chown sas:sas /modules
USER sas
ENV SAS_SCR_APP_PATH=/carlookup
COPY --chown=sas:sas unzipped/ /modules/
COPY --chown=sas:sas manifest/ /manifest/
COPY --from=base  /hiredis /
ENV LD_LIBRARY_PATH=/opt/scr/viya/home/SASFoundation/utilities/bin:/opt/scr/viya/home/SASFoundation/sasexe