services:
  scr:
    build: ./scr
    container_name: scr-solo
    ports:
      - 8081:8080
    environment:
      - SAS_SCR_LOG_LEVEL_SCR_CONFIG=TRACE
      - SAS_SCR_LOG_LEVEL_SCR_MODULE_LOGGER=TRACE
      - SAS_SCR_LOG_LEVEL_App=TRACE
      - SAS_SCR_LOG_LEVEL_Audit=TRACE
      - SAS_SCR_PASS_HEADERS=True
